language: node_js
node_js:
  - stable
install: "yarn install"
before_deploy: "yarn build"
cache: yarn
install: yarn
deploy:
  provider: npm
  script: "npm publish"
  skip_cleanup: true
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"

